### ISSUE TITLE
panic session session-closed

### ISSUE THREAD

**Issue by seven-ali** [dubbogo/getty#103]
**What happened**:
[session.WritePkg] panic session session-closed: err=runtime error: invalid memory address or nil pointer dereference
github.com/apache/dubbo-getty.(*gettyTCPConn).send(0xc01231a1c0, {0x16fd200, 0xc0116da948})
github.com/apache/dubbo-getty/connection.go:328 +0x3df

**What you expected to happen**:
not panic

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by No-SilverBullet** [comment]
since this PR(https://github.com/apache/dubbo-getty/pull/121) has merged, maybe we can close this issue @AlexStocks

**Comment by AlexStocks** [comment]
> since this PR(#121) has merged, maybe we can close this issue @AlexStocks

done
