### ISSUE TITLE
skip the log output of EOF error

### ISSUE THREAD

**Issue by gaoxinge** [dubbogo/getty#29]
https://github.com/dubbogo/getty/blob/c34c7a71a0e60c900c7855a83db2caa0bd1d6d8a/session.go#L718-L725

`conn.recv(buf)` may raise an EOF error when conn has read all bytes sent by client. This is not a network error, so I think we can skip the log output of this kind of error.

In consul registry, provider will register with [a tcp based health check](https://github.com/apache/dubbo-go/blob/ac51fc14019cb376e5b0feedc3e4ee80af029b17/registry/consul/utils.go#L78-L83). This tcp connection will send empty byte to service constantly, and we will get EOF errors constantly too:

![eof](https://user-images.githubusercontent.com/16648345/65825754-6304f680-e2ad-11e9-9c15-e755e8892921.jpg)

So skipping the log output of EOF error will make the console more clean.

**Comment by AlexStocks** [comment]
@gaoxinge Agree with u. U can issue a pr to improve it.
