### ISSUE TITLE
Session connection failed.

### ISSUE THREAD

**Issue by lllxbbb** [dubbogo/getty#99]
**What happened**: After the provider instance restart,the session is interrupted and the client keeps retrying the connection.As a result, error logs flood the screen.

**What you expected to happen**: I want the client not to reconnect indefinitely after the session is interrupted.

**How to reproduce it (as minimally and precisely as possible)**: After the provider instance restarts, use the client to invoke the Provider.

**Anything else we need to know?**: I found a loop call. 
dubbo-getty/session.go/handlePackage -> dubbo-getty/session.go/stop -> dubbo-getty/client.go/reConnect -> dubbo-getty/client.go/connect ->  dubbo-getty/session.go/run -> dubbo-getty/session.go/handlePackage

**Comment by AlexStocks** [comment]
你先读读 https://mp.weixin.qq.com/s/z22k-E2ybjAMNtxzj5Aikw 这篇文章，这个一直持续链接 就是框架这么设计的。你可以在client 上层调用 Close() 把它关掉。

**Comment by lllxbbb** [comment]
> 你先读读 https://mp.weixin.qq.com/s/z22k-E2ybjAMNtxzj5Aikw 这篇文章，这个一直持续链接 就是框架这么设计的。你可以在client 上层调用 Close() 把它关掉。

好的好的，谢谢。

**Comment by AlexStocks** [comment]
客气，有问题随时找我。
